### ISSUE TITLE
Incorrect repository URL in node/README.md

### ISSUE THREAD

**Issue by swoldemi** [smartcar/demo#16]
https://github.com/smartcar/getting-started does not exist but is referred to in https://github.com/smartcar/demo/tree/master/node/README.md as the clone source.

Although, Step 4 of the Getting Started page at https://support.smartcar.com/run-our-demo-app does correctly reference smartcar/demo 👍

**Comment by gurpreetatwal** [comment]
Hey @swoldemi thanks for catching this! We should have this fixed soon.

**Comment by gurpreetatwal** [comment]
Also, if you would like a Smartcar t-shirt, you can [email](mailto:gurpreet@smartcar.com) me your t-shirt size and shipping address and we'll send one over :shirt: :package: :ship:
