### ISSUE TITLE
404 "Create a Buick account"

### ISSUE THREAD

**Issue by html5cat** [smartcar/demo#7]
When you try to create an account on https://buick.smartcar.com/oauth/flow (or any other vendor it seems) you get a 404

**Comment by esonmez** [comment]
We're working on a fix for this now. In the meantime, please feel free to use [this link](https://my.gm.com/signup) to create an OnStart account for GM cars. Note: you'll need access to a GM car  to create an account. If you don't have one, feel free to [DM us](https://twitter.com/mysmartcar) to set up time to test on on of our test vehicles!!

**Comment by esonmez** [comment]
@html5cat this should be fixed now!

**Comment by html5cat** [comment]
That was fast. We landed in one piece too ✈️

**Comment by esonmez** [comment]
Wins all around!!
